--------------------------------------------------------
--  File created - Thursday-December-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHANNELS
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."CHANNELS" 
   (	"CHANNEL_ID" NUMBER, 
	"CHANNEL_DESC" VARCHAR2(20 BYTE), 
	"CHANNEL_CLASS" VARCHAR2(20 BYTE), 
	"CHANNEL_CLASS_ID" NUMBER, 
	"CHANNEL_TOTAL" VARCHAR2(13 BYTE), 
	"CHANNEL_TOTAL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DBT_USER"."CHANNELS"."CHANNEL_ID" IS 'primary key column';
   COMMENT ON COLUMN "DBT_USER"."CHANNELS"."CHANNEL_DESC" IS 'e.g. telesales, internet, catalog';
   COMMENT ON COLUMN "DBT_USER"."CHANNELS"."CHANNEL_CLASS" IS 'e.g. direct, indirect';
   COMMENT ON TABLE "DBT_USER"."CHANNELS"  IS 'small dimension table';
--------------------------------------------------------
--  DDL for Table COSTS
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."COSTS" 
   (	"PROD_ID" NUMBER, 
	"TIME_ID" DATE, 
	"PROMO_ID" NUMBER, 
	"CHANNEL_ID" NUMBER, 
	"UNIT_COST" NUMBER(10,2), 
	"UNIT_PRICE" NUMBER(10,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARTITION BY RANGE ("TIME_ID") 
 (PARTITION "COSTS_Q1_2019"  VALUES LESS THAN (TO_DATE(' 2019-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q2_2019"  VALUES LESS THAN (TO_DATE(' 2019-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q3_2019"  VALUES LESS THAN (TO_DATE(' 2019-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q4_2019"  VALUES LESS THAN (TO_DATE(' 2020-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q1_2020"  VALUES LESS THAN (TO_DATE(' 2020-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q2_2020"  VALUES LESS THAN (TO_DATE(' 2020-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q3_2020"  VALUES LESS THAN (TO_DATE(' 2020-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q4_2020"  VALUES LESS THAN (TO_DATE(' 2021-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q1_2021"  VALUES LESS THAN (TO_DATE(' 2021-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q2_2021"  VALUES LESS THAN (TO_DATE(' 2021-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q3_2021"  VALUES LESS THAN (TO_DATE(' 2021-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q4_2021"  VALUES LESS THAN (TO_DATE(' 2022-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q1_2022"  VALUES LESS THAN (TO_DATE(' 2022-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q2_2022"  VALUES LESS THAN (TO_DATE(' 2022-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q3_2022"  VALUES LESS THAN (TO_DATE(' 2022-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q4_2022"  VALUES LESS THAN (TO_DATE(' 2023-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q1_2023"  VALUES LESS THAN (TO_DATE(' 2023-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q2_2023"  VALUES LESS THAN (TO_DATE(' 2023-07-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q3_2023"  VALUES LESS THAN (TO_DATE(' 2023-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COMPRESS BASIC LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" , 
 PARTITION "COSTS_Q4_2023"  VALUES LESS THAN (TO_DATE(' 2024-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) ;
--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."COUNTRIES" 
   (	"COUNTRY_ID" NUMBER, 
	"COUNTRY_ISO_CODE" CHAR(2 BYTE), 
	"COUNTRY_NAME" VARCHAR2(40 BYTE), 
	"COUNTRY_SUBREGION" VARCHAR2(30 BYTE), 
	"COUNTRY_SUBREGION_ID" NUMBER, 
	"COUNTRY_REGION" VARCHAR2(20 BYTE), 
	"COUNTRY_REGION_ID" NUMBER, 
	"COUNTRY_TOTAL" VARCHAR2(11 BYTE), 
	"COUNTRY_TOTAL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DBT_USER"."COUNTRIES"."COUNTRY_ID" IS 'primary key';
   COMMENT ON COLUMN "DBT_USER"."COUNTRIES"."COUNTRY_NAME" IS 'country name';
   COMMENT ON COLUMN "DBT_USER"."COUNTRIES"."COUNTRY_SUBREGION" IS 'e.g. Western Europe, to allow hierarchies';
   COMMENT ON COLUMN "DBT_USER"."COUNTRIES"."COUNTRY_REGION" IS 'e.g. Europe, Asia';
   COMMENT ON TABLE "DBT_USER"."COUNTRIES"  IS 'country dimension table (snowflake)';
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."CUSTOMERS" 
   (	"CUST_ID" NUMBER, 
	"CUST_FIRST_NAME" VARCHAR2(20 BYTE), 
	"CUST_LAST_NAME" VARCHAR2(40 BYTE), 
	"CUST_GENDER" CHAR(1 BYTE), 
	"CUST_YEAR_OF_BIRTH" NUMBER(4,0), 
	"CUST_MARITAL_STATUS" VARCHAR2(20 BYTE), 
	"CUST_STREET_ADDRESS" VARCHAR2(40 BYTE), 
	"CUST_POSTAL_CODE" VARCHAR2(10 BYTE), 
	"CUST_CITY" VARCHAR2(30 BYTE), 
	"CUST_CITY_ID" NUMBER, 
	"CUST_STATE_PROVINCE" VARCHAR2(40 BYTE), 
	"CUST_STATE_PROVINCE_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"CUST_MAIN_PHONE_NUMBER" VARCHAR2(25 BYTE), 
	"CUST_INCOME_LEVEL" VARCHAR2(30 BYTE), 
	"CUST_CREDIT_LIMIT" NUMBER, 
	"CUST_EMAIL" VARCHAR2(50 BYTE), 
	"CUST_TOTAL" VARCHAR2(14 BYTE), 
	"CUST_TOTAL_ID" NUMBER, 
	"CUST_SRC_ID" NUMBER, 
	"CUST_EFF_FROM" DATE, 
	"CUST_EFF_TO" DATE, 
	"CUST_VALID" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_ID" IS 'primary key';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_FIRST_NAME" IS 'first name of the customer';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_LAST_NAME" IS 'last name of the customer';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_GENDER" IS 'gender; low cardinality attribute';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_YEAR_OF_BIRTH" IS 'customer year of birth';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_MARITAL_STATUS" IS 'customer marital status; low cardinality attribute';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_STREET_ADDRESS" IS 'customer street address';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_POSTAL_CODE" IS 'postal code of the customer';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_CITY" IS 'city where the customer lives';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_STATE_PROVINCE" IS 'customer geography: state or province';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."COUNTRY_ID" IS 'foreign key to the countries table (snowflake)';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_MAIN_PHONE_NUMBER" IS 'customer main phone number';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_INCOME_LEVEL" IS 'customer income level';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_CREDIT_LIMIT" IS 'customer credit limit';
   COMMENT ON COLUMN "DBT_USER"."CUSTOMERS"."CUST_EMAIL" IS 'customer email id';
   COMMENT ON TABLE "DBT_USER"."CUSTOMERS"  IS 'dimension table';
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."PRODUCTS" 
   (	"PROD_ID" NUMBER(6,0), 
	"PROD_NAME" VARCHAR2(50 BYTE), 
	"PROD_DESC" VARCHAR2(4000 BYTE), 
	"PROD_SUBCATEGORY" VARCHAR2(50 BYTE), 
	"PROD_SUBCATEGORY_ID" NUMBER, 
	"PROD_SUBCATEGORY_DESC" VARCHAR2(2000 BYTE), 
	"PROD_CATEGORY" VARCHAR2(50 BYTE), 
	"PROD_CATEGORY_ID" NUMBER, 
	"PROD_CATEGORY_DESC" VARCHAR2(2000 BYTE), 
	"PROD_WEIGHT_CLASS" NUMBER(3,0), 
	"PROD_UNIT_OF_MEASURE" VARCHAR2(20 BYTE), 
	"PROD_PACK_SIZE" VARCHAR2(30 BYTE), 
	"SUPPLIER_ID" NUMBER(6,0), 
	"PROD_STATUS" VARCHAR2(20 BYTE), 
	"PROD_LIST_PRICE" NUMBER(8,2), 
	"PROD_MIN_PRICE" NUMBER(8,2), 
	"PROD_TOTAL" VARCHAR2(13 BYTE), 
	"PROD_TOTAL_ID" NUMBER, 
	"PROD_SRC_ID" NUMBER, 
	"PROD_EFF_FROM" DATE, 
	"PROD_EFF_TO" DATE, 
	"PROD_VALID" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_ID" IS 'primary key';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_NAME" IS 'product name';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_DESC" IS 'product description';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_SUBCATEGORY" IS 'product subcategory';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_SUBCATEGORY_DESC" IS 'product subcategory description';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_CATEGORY" IS 'product category';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_CATEGORY_DESC" IS 'product category description';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_WEIGHT_CLASS" IS 'product weight class';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_UNIT_OF_MEASURE" IS 'product unit of measure';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_PACK_SIZE" IS 'product package size';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."SUPPLIER_ID" IS 'this column';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_STATUS" IS 'product status';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_LIST_PRICE" IS 'product list price';
   COMMENT ON COLUMN "DBT_USER"."PRODUCTS"."PROD_MIN_PRICE" IS 'product minimum price';
   COMMENT ON TABLE "DBT_USER"."PRODUCTS"  IS 'dimension table';
--------------------------------------------------------
--  DDL for Table PROMOTIONS
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."PROMOTIONS" 
   (	"PROMO_ID" NUMBER(6,0), 
	"PROMO_NAME" VARCHAR2(30 BYTE), 
	"PROMO_SUBCATEGORY" VARCHAR2(30 BYTE), 
	"PROMO_SUBCATEGORY_ID" NUMBER, 
	"PROMO_CATEGORY" VARCHAR2(30 BYTE), 
	"PROMO_CATEGORY_ID" NUMBER, 
	"PROMO_COST" NUMBER(10,2), 
	"PROMO_BEGIN_DATE" DATE, 
	"PROMO_END_DATE" DATE, 
	"PROMO_TOTAL" VARCHAR2(15 BYTE), 
	"PROMO_TOTAL_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DBT_USER"."PROMOTIONS"."PROMO_ID" IS 'primary key column';
   COMMENT ON COLUMN "DBT_USER"."PROMOTIONS"."PROMO_NAME" IS 'promotion description';
   COMMENT ON COLUMN "DBT_USER"."PROMOTIONS"."PROMO_SUBCATEGORY" IS 'enables to investigate promotion hierarchies';
   COMMENT ON COLUMN "DBT_USER"."PROMOTIONS"."PROMO_CATEGORY" IS 'promotion category';
   COMMENT ON COLUMN "DBT_USER"."PROMOTIONS"."PROMO_COST" IS 'promotion cost, to do promotion effect calculations';
   COMMENT ON COLUMN "DBT_USER"."PROMOTIONS"."PROMO_BEGIN_DATE" IS 'promotion begin day';
   COMMENT ON COLUMN "DBT_USER"."PROMOTIONS"."PROMO_END_DATE" IS 'promotion end day';
   COMMENT ON TABLE "DBT_USER"."PROMOTIONS"  IS 'dimension table without a PK-FK relationship with the facts table, to show outer join functionality';
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."SALES" 
   (	"PROD_ID" NUMBER(6,0), 
	"CUST_ID" NUMBER, 
	"TIME_ID" DATE, 
	"CHANNEL_ID" NUMBER(1,0), 
	"PROMO_ID" NUMBER(6,0), 
	"QUANTITY_SOLD" NUMBER(3,0), 
	"AMOUNT_SOLD" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUPPLEMENTARY_DEMOGRAPHICS
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."SUPPLEMENTARY_DEMOGRAPHICS" 
   (	"CUST_ID" NUMBER, 
	"EDUCATION" VARCHAR2(21 BYTE), 
	"OCCUPATION" VARCHAR2(21 BYTE), 
	"HOUSEHOLD_SIZE" VARCHAR2(21 BYTE), 
	"YRS_RESIDENCE" NUMBER, 
	"AFFINITY_CARD" NUMBER(10,0), 
	"CRICKET" NUMBER(10,0), 
	"BASEBALL" NUMBER(10,0), 
	"TENNIS" NUMBER(10,0), 
	"SOCCER" NUMBER(10,0), 
	"GOLF" NUMBER(10,0), 
	"UNKNOWN" NUMBER(10,0), 
	"MISC" NUMBER(10,0), 
	"COMMENTS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST_MIGRATION
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."TEST_MIGRATION" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE, 
	"AMOUNT" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIMES
--------------------------------------------------------

  CREATE TABLE "DBT_USER"."TIMES" 
   (	"TIME_ID" DATE, 
	"DAY_NAME" VARCHAR2(9 BYTE), 
	"DAY_NUMBER_IN_WEEK" NUMBER(1,0), 
	"DAY_NUMBER_IN_MONTH" NUMBER(2,0), 
	"CALENDAR_WEEK_NUMBER" NUMBER(2,0), 
	"FISCAL_WEEK_NUMBER" NUMBER(2,0), 
	"WEEK_ENDING_DAY" DATE, 
	"WEEK_ENDING_DAY_ID" NUMBER, 
	"CALENDAR_MONTH_NUMBER" NUMBER(2,0), 
	"FISCAL_MONTH_NUMBER" NUMBER(2,0), 
	"CALENDAR_MONTH_DESC" VARCHAR2(8 BYTE), 
	"CALENDAR_MONTH_ID" NUMBER, 
	"FISCAL_MONTH_DESC" VARCHAR2(8 BYTE), 
	"FISCAL_MONTH_ID" NUMBER, 
	"DAYS_IN_CAL_MONTH" NUMBER, 
	"DAYS_IN_FIS_MONTH" NUMBER, 
	"END_OF_CAL_MONTH" DATE, 
	"END_OF_FIS_MONTH" DATE, 
	"CALENDAR_MONTH_NAME" VARCHAR2(9 BYTE), 
	"FISCAL_MONTH_NAME" VARCHAR2(9 BYTE), 
	"CALENDAR_QUARTER_DESC" CHAR(7 BYTE), 
	"CALENDAR_QUARTER_ID" NUMBER, 
	"FISCAL_QUARTER_DESC" CHAR(7 BYTE), 
	"FISCAL_QUARTER_ID" NUMBER, 
	"DAYS_IN_CAL_QUARTER" NUMBER, 
	"DAYS_IN_FIS_QUARTER" NUMBER, 
	"END_OF_CAL_QUARTER" DATE, 
	"END_OF_FIS_QUARTER" DATE, 
	"CALENDAR_QUARTER_NUMBER" NUMBER(1,0), 
	"FISCAL_QUARTER_NUMBER" NUMBER(1,0), 
	"CALENDAR_YEAR" NUMBER(4,0), 
	"CALENDAR_YEAR_ID" NUMBER, 
	"FISCAL_YEAR" NUMBER(4,0), 
	"FISCAL_YEAR_ID" NUMBER, 
	"DAYS_IN_CAL_YEAR" NUMBER, 
	"DAYS_IN_FIS_YEAR" NUMBER, 
	"END_OF_CAL_YEAR" DATE, 
	"END_OF_FIS_YEAR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DBT_USER"."TIMES"."TIME_ID" IS 'primary key; day date, finest granularity, CORRECT ORDER';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."DAY_NAME" IS 'Monday to Sunday, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."DAY_NUMBER_IN_WEEK" IS '1 to 7, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."DAY_NUMBER_IN_MONTH" IS '1 to 31, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."CALENDAR_WEEK_NUMBER" IS '1 to 53, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."FISCAL_WEEK_NUMBER" IS '1 to 53, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."WEEK_ENDING_DAY" IS 'date of last day in week, CORRECT ORDER';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."CALENDAR_MONTH_NUMBER" IS '1 to 12, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."FISCAL_MONTH_NUMBER" IS '1 to 12, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."CALENDAR_MONTH_DESC" IS 'e.g. 1998-01, CORRECT ORDER';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."FISCAL_MONTH_DESC" IS 'e.g. 1998-01, CORRECT ORDER';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."DAYS_IN_CAL_MONTH" IS 'e.g. 28,31, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."DAYS_IN_FIS_MONTH" IS 'e.g. 25,32, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."END_OF_CAL_MONTH" IS 'last day of calendar month';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."END_OF_FIS_MONTH" IS 'last day of fiscal month';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."CALENDAR_MONTH_NAME" IS 'January to December, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."FISCAL_MONTH_NAME" IS 'January to December, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."CALENDAR_QUARTER_DESC" IS 'e.g. 1998-Q1, CORRECT ORDER';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."FISCAL_QUARTER_DESC" IS 'e.g. 1999-Q3, CORRECT ORDER';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."DAYS_IN_CAL_QUARTER" IS 'e.g. 88,90, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."DAYS_IN_FIS_QUARTER" IS 'e.g. 88,90, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."END_OF_CAL_QUARTER" IS 'last day of calendar quarter';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."END_OF_FIS_QUARTER" IS 'last day of fiscal quarter';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."CALENDAR_QUARTER_NUMBER" IS '1 to 4, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."FISCAL_QUARTER_NUMBER" IS '1 to 4, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."CALENDAR_YEAR" IS 'e.g. 1999, CORRECT ORDER';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."FISCAL_YEAR" IS 'e.g. 1999, CORRECT ORDER';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."DAYS_IN_CAL_YEAR" IS '365,366 repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."DAYS_IN_FIS_YEAR" IS 'e.g. 355,364, repeating';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."END_OF_CAL_YEAR" IS 'last day of cal year';
   COMMENT ON COLUMN "DBT_USER"."TIMES"."END_OF_FIS_YEAR" IS 'last day of fiscal year';
   COMMENT ON TABLE "DBT_USER"."TIMES"  IS 'Time dimension table to support multiple hierarchies and materialized views';
